# Generated by Django 5.2.4 on 2025-08-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_customuserquizz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
